Feat shopping cart
dlvsn/online-book-store pull request #11
Opened 2024-12-08 20:47 UTC by dlvsn

2024-12-09 14:13 UTC, Elena-Bruyako requested changes
see comments

2024-12-09 14:13 UTC, Elena-Bruyako commented on src/main/java/org/example/onlinebookstore/controller/ShoppingCartController.java
> +                                                         @RequestBody CartItemRequestDto cartItem) {
```suggestion
                                                         @RequestBody @Valid CartItemRequestDto cartItem) {
```

2024-12-09 14:13 UTC, Elena-Bruyako commented on src/main/java/org/example/onlinebookstore/controller/ShoppingCartController.java
> +                                                  @RequestBody UpdateCartItemRequestDto cartItem) {
```suggestion
                                                  @RequestBody @Valid UpdateCartItemRequestDto cartItem) {
```

2024-12-09 14:13 UTC, Elena-Bruyako commented on src/main/java/org/example/onlinebookstore/dto/cartitem/UpdateCartItemRequestDto.java
> +public record UpdateCartItemRequestDto(int quantity) {
validate quantity

2024-12-09 14:13 UTC, Elena-Bruyako commented on src/main/java/org/example/onlinebookstore/dto/cartitem/CartItemRequestDto.java
> +public record CartItemRequestDto(Long bookId,
validate bookId and quantity

2024-12-09 14:13 UTC, Elena-Bruyako commented on src/main/java/org/example/onlinebookstore/mapper/ShoppingCartMapper.java
> +    @Mapping(target = "cartItems", source = "cartItems")
```suggestion
```

2024-12-12 17:12 UTC, Elena-Bruyako requested changes
see comments

2024-12-12 17:12 UTC, Elena-Bruyako commented on src/main/java/org/example/onlinebookstore/dto/cartitem/CartItemRequestDto.java
> +public record CartItemRequestDto(@Min(value = 1, message = "book id can't be less than 1")
```suggestion
public record CartItemRequestDto(@NotNull @Positive(value = 1, message = "book id can't be less than 1")
```

2024-12-12 17:12 UTC, Elena-Bruyako commented on src/main/java/org/example/onlinebookstore/dto/cartitem/CartItemRequestDto.java
> +                                 @Min(value = 1, message = "quantity can't be less than 1")
```suggestion
                                 @Positive(value = 1, message = "quantity can't be less than 1")
```

2024-12-12 17:12 UTC, Elena-Bruyako commented on src/main/java/org/example/onlinebookstore/dto/cartitem/UpdateCartItemRequestDto.java
> +        @Min(value = 1, message = "quantity can't be less than 1")
```suggestion
        @Positive(value = 1, message = "quantity can't be less than 1")
```

2024-12-12 17:12 UTC, Elena-Bruyako commented on src/main/java/org/example/onlinebookstore/repository/shoppingcart/CartItemRepository.java
> +
```suggestion
```

2024-12-12 17:12 UTC, Elena-Bruyako commented on src/main/java/org/example/onlinebookstore/service/shoppingcart/ShoppingCartServiceImpl.java
> +    @Override
```suggestion
    @Override
    @Transactional
```

2024-12-13 07:59 UTC, liliia-ponomarenko requested changes
Good job! Let’s  fix a few mistakes ;)

2024-12-13 07:59 UTC, liliia-ponomarenko commented on src/main/java/org/example/onlinebookstore/dto/cartitem/CartItemRequestDto.java
> +                                 @NotNull
primitive type can’t  be null

2024-12-13 07:59 UTC, liliia-ponomarenko commented on src/main/java/org/example/onlinebookstore/model/CartItem.java
> +
```suggestion
```

2024-12-13 07:59 UTC, liliia-ponomarenko commented on src/main/java/org/example/onlinebookstore/repository/shoppingcart/CartItemRepository.java
> +            + "WHERE item.id = ?1 AND item.shoppingCart.id = ?3")
do you really need a query? can you use CrudRepository methods?

2024-12-13 07:59 UTC, liliia-ponomarenko commented on src/main/java/org/example/onlinebookstore/repository/shoppingcart/CartItemRepository.java
> +    int deleteByIdAndShoppingCartId(Long id, Long shoppingCartId);
the same

2024-12-13 07:59 UTC, liliia-ponomarenko commented on src/main/java/org/example/onlinebookstore/repository/shoppingcart/ShoppingCartRepository.java
> +    ShoppingCart findByUserId(Long userId);
better return Optional

2024-12-13 07:59 UTC, liliia-ponomarenko commented on src/main/java/org/example/onlinebookstore/service/shoppingcart/ShoppingCartServiceImpl.java
> +    @Override
not fixed

2024-12-13 07:59 UTC, liliia-ponomarenko commented on src/main/java/org/example/onlinebookstore/service/user/UserServiceImpl.java
> +        shoppingCartService.registerNewShoppingCart(newUser);
you should use the Transactional annotation above this method

2024-12-13 07:59 UTC, liliia-ponomarenko commented on src/main/resources/db/changelog/changes/12-create-cart-item-table.yaml
> +                  defaultValue: "1"
do you really need a default value here?

2024-12-14 11:18 UTC, dlvsn commented on src/main/resources/db/changelog/changes/12-create-cart-item-table.yaml
> +                  defaultValue: "1"
I done rollback, and refactored this file

2024-12-15 12:14 UTC, Elena-Bruyako requested changes
see comments

2024-12-15 12:14 UTC, Elena-Bruyako commented on src/main/java/org/example/onlinebookstore/service/shoppingcart/ShoppingCartServiceImpl.java
> +    @Transactional
```suggestion
    @Transactional
    @Override
```

2024-12-15 12:14 UTC, Elena-Bruyako commented on src/main/java/org/example/onlinebookstore/service/shoppingcart/ShoppingCartServiceImpl.java
> +    @Transactional
```suggestion
    @Transactional
    @Override
```

2024-12-15 12:14 UTC, Elena-Bruyako commented on src/main/java/org/example/onlinebookstore/service/shoppingcart/ShoppingCartServiceImpl.java
> +    @Transactional
```suggestion
    @Transactional
    @Override
```

2024-12-15 12:14 UTC, Elena-Bruyako commented on src/main/java/org/example/onlinebookstore/service/user/UserServiceImpl.java
> +    @Transactional
```suggestion
    @Transactional
    @Override
```

2024-12-15 12:14 UTC, Elena-Bruyako commented on src/main/java/org/example/onlinebookstore/service/user/UserServiceImpl.java
> +        shoppingCartService.registerNewShoppingCart(newUser);
```suggestion
        newUser.setRoles(Set.of(roleUser));
        userRepository.save(newUser);
        shoppingCartService.registerNewShoppingCart(newUser);
        return userMapper.toDto(newUser);
```

2024-12-16 12:13 UTC, dlvsn commented on src/main/java/org/example/onlinebookstore/service/user/UserServiceImpl.java
> +        shoppingCartService.registerNewShoppingCart(newUser);
if i use newUser.setRoles(Set.of(roleUser)); i get error java.lang.UnsupportedOperationException: null
	at java.base/java.util.ImmutableCollections.uoe(ImmutableCollections.java:142) ~[na:na]
	when i try to save user to db

2024-12-21 15:20 UTC, dlvsn commented on src/main/java/org/example/onlinebookstore/service/user/UserServiceImpl.java
> +        shoppingCartService.registerNewShoppingCart(newUser);
I visited q&a and Artur told me, that i can write like this newUser.setRoles(new HashSet<>(Set.of(roleUser)));

2024-12-21 16:52 UTC, liliia-ponomarenko requested changes
Good job! Let’s fix all previous comments ;)

2024-12-21 16:52 UTC, liliia-ponomarenko commented on src/main/java/org/example/onlinebookstore/service/shoppingcart/ShoppingCartServiceImpl.java
> +    @Transactional
not fixed. Override annotation missed

2024-12-21 16:52 UTC, liliia-ponomarenko commented on src/main/java/org/example/onlinebookstore/service/shoppingcart/ShoppingCartServiceImpl.java
> +    public ShoppingCartResponseDto removeItemFromShoppingCart(User user, Long itemId) {
not fixed. Override annotation missed

2024-12-21 16:52 UTC, liliia-ponomarenko commented on src/main/java/org/example/onlinebookstore/service/user/UserServiceImpl.java
> +    @Transactional
the same

2024-12-21 16:52 UTC, liliia-ponomarenko commented on src/main/java/org/example/onlinebookstore/service/user/UserServiceImpl.java
> +        shoppingCartService.registerNewShoppingCart(newUser);
Elena's comment also referred to the fact that you need to save the user first and then the shopping cart

2024-12-25 15:33 UTC, JJJazl approved these changes

2024-12-25 15:33 UTC, JJJazl commented on src/main/java/org/example/onlinebookstore/repository/shoppingcart/ShoppingCartRepository.java
> +    Optional<ShoppingCart> findByUserId(Long userId);
```suggestion
    Optional<ShoppingCart> findByUserIdFetchCartItemsAndBooks(Long userId);
```

2024-12-25 15:33 UTC, JJJazl commented on src/main/java/org/example/onlinebookstore/service/shoppingcart/ShoppingCartServiceImpl.java
> +@Service
You can use `@Transactional` on a class and it will automatically affect all methods because Spring creates a proxy of your class.
By the way, even 1 method marked with `@Transactional` will have the same effect

2024-12-27 07:29 UTC, merged