Feat order
dlvsn/online-book-store pull request #12
Opened 2024-12-13 07:14 UTC by dlvsn

2024-12-13 08:17 UTC, liliia-ponomarenko requested changes
Good job! Let’s  improve your solution ;)

2024-12-13 08:17 UTC, liliia-ponomarenko commented on src/main/java/org/example/onlinebookstore/controller/BookController.java
> +                                       @Positive Long id) {
This annotation doesn’t work without Validated above class

2024-12-13 08:17 UTC, liliia-ponomarenko commented on src/main/java/org/example/onlinebookstore/controller/OrderController.java
> +@RequestMapping("/orders")
Validated missed

2024-12-13 08:17 UTC, liliia-ponomarenko commented on src/main/java/org/example/onlinebookstore/controller/OrderController.java
> +    @PostMapping
ResponseStatus.CREATED

2024-12-13 08:17 UTC, liliia-ponomarenko commented on src/main/java/org/example/onlinebookstore/dto/book/CreateBookRequestDto.java
> +    @Positive(message = "price can't be less than 1")
use NotNull with Positive

2024-12-13 08:17 UTC, liliia-ponomarenko commented on src/main/java/org/example/onlinebookstore/dto/order/OrderResponseDto.java
> +                               int totalPrice,
for price better use BigDecimal

2024-12-13 08:17 UTC, liliia-ponomarenko commented on src/main/java/org/example/onlinebookstore/dto/order/PlaceOrderRequestDto.java
> +public record PlaceOrderRequestDto(String shippingAddress) {
should you validate request dto?

2024-12-13 08:17 UTC, liliia-ponomarenko commented on src/main/java/org/example/onlinebookstore/dto/order/UpdateOrderStatusRequestDto.java
> +                                          String status) {
better use Order.Status

2024-12-13 08:17 UTC, liliia-ponomarenko commented on src/main/java/org/example/onlinebookstore/model/Order.java
> +    @ManyToOne
Use lazy fetch type

2024-12-13 08:17 UTC, liliia-ponomarenko commented on src/main/java/org/example/onlinebookstore/model/Order.java
> +    private LocalDateTime orderDate = LocalDateTime.now();
you can use the CreatedTimestamp annotation

2024-12-13 08:17 UTC, liliia-ponomarenko commented on src/main/java/org/example/onlinebookstore/model/Order.java
> +    @OneToMany(mappedBy = "order", cascade = CascadeType.PERSIST)
```suggestion
    @OneToMany(mappedBy = "order", cascade = CascadeType.ALL, orphanRemoval = true)
```

2024-12-13 08:17 UTC, liliia-ponomarenko commented on src/main/java/org/example/onlinebookstore/repository/order/OrderItemRepository.java
> +            + "WHERE oi.id = :id AND o.id = :orderId AND o.user.id = :userId")
do you really need a custom query?

2024-12-13 08:17 UTC, liliia-ponomarenko commented on src/main/java/org/example/onlinebookstore/repository/order/OrderItemRepository.java
> +
```suggestion
```

2024-12-13 08:17 UTC, liliia-ponomarenko commented on src/main/java/org/example/onlinebookstore/repository/order/OrderRepository.java
> +    int updateOrderById(Long id, Order.Status status);
the same

2024-12-13 08:17 UTC, liliia-ponomarenko commented on src/main/java/org/example/onlinebookstore/service/order/OrderServiceImpl.java
> +    public OrderResponseDto placeOrder(User user, PlaceOrderRequestDto placeOrderRequestDto) {
do you need Transactional here?

2024-12-13 08:17 UTC, liliia-ponomarenko commented on src/main/java/org/example/onlinebookstore/service/order/OrderServiceImpl.java
> +            throw new DataProcessingException("Can't place order. Cart is empty");
Let’s  provide some parameters

2024-12-13 08:17 UTC, liliia-ponomarenko commented on src/main/java/org/example/onlinebookstore/service/order/OrderServiceImpl.java
> +        if (shippingAddress == null || shippingAddress.isBlank()) {
better validate this parameter on dto level

2024-12-13 08:17 UTC, liliia-ponomarenko commented on src/main/java/org/example/onlinebookstore/service/order/OrderServiceImpl.java
> +                .orElseThrow(() -> new EntityNotFoundException("Can't find"));
not informative message

2024-12-13 08:17 UTC, liliia-ponomarenko commented on src/main/java/org/example/onlinebookstore/service/order/OrderServiceImpl.java
> +                }).collect(Collectors.toSet());
```suggestion
                }).toSet();
```

2024-12-13 08:17 UTC, liliia-ponomarenko commented on src/main/resources/db/changelog/changes/13-create-order-table.yaml
> +
```suggestion
```
only one empty line

2024-12-14 07:58 UTC, dlvsn commented on src/main/java/org/example/onlinebookstore/service/order/OrderServiceImpl.java
> +                }).collect(Collectors.toSet());
I have compilation error if i don't use .collect(Collectors.toSet());

2024-12-14 08:00 UTC, dlvsn commented on src/main/java/org/example/onlinebookstore/repository/order/OrderItemRepository.java
> +            + "WHERE oi.id = :id AND o.id = :orderId AND o.user.id = :userId")
Yes, because any other authorized user can get other user's orders

2024-12-16 06:47 UTC, liliia-ponomarenko approved these changes
Good job! 👍

2024-12-16 06:47 UTC, liliia-ponomarenko commented on src/main/java/org/example/onlinebookstore/service/order/OrderServiceImpl.java
> +        return requestDto.shippingAddress() != null && !requestDto.shippingAddress().isBlank()
Is it possible? In your business logic, you use shippingAddress that the user passes with placing request

2024-12-27 07:46 UTC, merged