Test for book/categories functionality
dlvsn/online-book-store pull request #14
Opened 2024-12-26 08:12 UTC by dlvsn

<img width="624" alt="service coverage" src="https://github.com/user-attachments/assets/bc94cd38-bd45-46f8-abeb-17fd27051243" />
<img width="623" alt="repository coverage" src="https://github.com/user-attachments/assets/09fb693b-d839-4910-b095-0ce9cb6c148b" />
<img width="642" alt="controllers coverage" src="https://github.com/user-attachments/assets/43abfbe0-ecf7-4198-85b0-6a607a22b452" />

2024-12-26 08:58 UTC, liliia-ponomarenko requested changes
Good job! Let’s  improve your solution ;)

2024-12-26 08:58 UTC, liliia-ponomarenko commented on src/test/java/org/example/onlinebookstore/controller/BookControllerTest.java
> +        ).andExpect(status().isForbidden());
This is about security testing, not books. Better test the bad request and not found responses

2024-12-26 08:58 UTC, liliia-ponomarenko commented on src/test/java/org/example/onlinebookstore/controller/CategoryControllerTest.java
> +public class CategoryControllerTest {
the same for the category

2024-12-26 08:58 UTC, liliia-ponomarenko commented on src/test/java/org/example/onlinebookstore/repository/book/BookRepositoryTest.java
> +                "Test book 1",
better move it to the private method and simplify this test case

2024-12-26 08:58 UTC, liliia-ponomarenko commented on src/test/java/org/example/onlinebookstore/service/category/CategoryServiceImplTest.java
> +    void saveCategory_Success() {
I recommend you use Given-When-Then construction

2024-12-26 08:58 UTC, liliia-ponomarenko commented on src/test/resources/database/test/books/delete-books-categories.sql
> +delete from books_categories;
add one empty line at the end of the file (check other files )

2024-12-26 08:58 UTC, liliia-ponomarenko commented on src/test/java/org/example/onlinebookstore/service/book/BookServiceImplTest.java
> +        BookSearchParameters bookSearchParameters = new BookSearchParameters(
can you use Builder?

2024-12-29 16:51 UTC, Elena-Bruyako approved these changes

2025-01-03 18:03 UTC, merged