Put/delete methods
dlvsn/online-book-store pull request #3
Opened 2024-10-26 15:16 UTC by dlvsn

2024-10-26 15:23 UTC, dlvsn commented
I don't know how to fix problems with ci

2024-10-26 15:25 UTC, dlvsn commented
everything works on my computer

2024-10-26 16:24 UTC, Elena-Bruyako requested changes
see comments

2024-10-26 16:24 UTC, Elena-Bruyako commented on src/main/java/org/example/onlinebookstore/controller/BookController.java
> +    @ResponseStatus(HttpStatus.ACCEPTED)
```suggestion
    @ResponseStatus(HttpStatus.NO_CONTENT)
```

2024-10-26 16:24 UTC, Elena-Bruyako commented on src/main/java/org/example/onlinebookstore/service/BookServiceImpl.java
> +        return bookMapper.toDto(bookRepository.save(model));
```suggestion
        bookMapper.updateBookFromDto(bookDto, book);
        return bookMapper.toDto(bookRepository.save(model));
```

2024-10-26 16:24 UTC, Elena-Bruyako commented on src/main/java/org/example/onlinebookstore/service/BookServiceImpl.java
> +        Book model = bookMapper.toModel(bookDto);
```suggestion
        Book book = bookMapper.toModel(bookDto);
```

2024-10-26 16:24 UTC, Elena-Bruyako commented on pom.xml
>              <groupId>org.projectlombok</groupId>
you have duplicate lombok dependency, remove one of them

2024-10-26 16:24 UTC, Elena-Bruyako commented on pom.xml
> +                </executions>
remove
```suggestion
```

2024-10-28 08:47 UTC, liliia-ponomarenko approved these changes
Good job! A few minor comments;)

2024-10-28 08:47 UTC, liliia-ponomarenko commented on src/main/java/org/example/onlinebookstore/controller/BookController.java
> +    @ResponseStatus(HttpStatus.OK)
it's default status code, so you can remove this annotation

2024-10-28 08:47 UTC, liliia-ponomarenko commented on src/main/java/org/example/onlinebookstore/controller/BookController.java
> +
```suggestion
```

2024-10-28 08:47 UTC, liliia-ponomarenko commented on src/main/resources/db/changelog/changes/01-create-book-table.yaml
> +                    nullable: false
add one empty line to the end of the file ;)

2024-10-28 09:34 UTC, merged