Jwt
dlvsn/online-book-store pull request #9
Opened 2024-11-10 17:46 UTC by dlvsn

2024-11-11 18:27 UTC, dlvsn commented
Please, help me to fix this problem

2024-11-11 19:16 UTC, dlvsn commented
i have errors, if i don't use annotation (@Column(name = "..")) above name field in roles table

2024-11-12 08:25 UTC, liliia-ponomarenko requested changes
Good job! Let’s  improve your solution ;)

2024-11-12 08:25 UTC, liliia-ponomarenko commented on src/main/java/org/example/onlinebookstore/security/JwtAuthenticationFilter.java
> +        String bearerToken = request.getHeader("Authorization");
```suggestion
        String bearerToken = request.getHeader(HttpHeaders.AUTORIZATION);
```

2024-11-12 08:25 UTC, liliia-ponomarenko commented on src/main/java/org/example/onlinebookstore/security/JwtAuthenticationFilter.java
> +        if (StringUtils.hasText(bearerToken) && bearerToken.startsWith("Bearer ")) {
Create constant

2024-11-12 08:25 UTC, liliia-ponomarenko commented on src/main/java/org/example/onlinebookstore/security/JwtAuthenticationFilter.java
> +            return bearerToken.substring(7);
```suggestion
            return bearerToken.substring(BEARER_PREFIX.length());
```

2024-11-12 08:25 UTC, liliia-ponomarenko commented on src/main/java/org/example/onlinebookstore/model/Role.java
> +    @Column(nullable = false, unique = true)
refactor liquibase script (or create new one). Use  `name` instead of `role_name` for this column to avoid validation exceptions.

2024-11-26 21:26 UTC, sarakhmen requested changes
let's improve your solution :)

2024-11-26 21:26 UTC, sarakhmen commented on src/main/java/org/example/onlinebookstore/config/SecurityConfig.java
>                  .httpBasic(withDefaults())
do you really need this line of config?

2024-11-26 21:26 UTC, sarakhmen commented on src/main/java/org/example/onlinebookstore/security/JwtAuthenticationFilter.java
> +    private static final String AUTHORIZATION_HEADER = "Authorization";
don't create your own constants as there already are out of the box ones declared for your needs :)

2024-11-29 13:46 UTC, sarakhmen approved these changes

2024-11-29 20:54 UTC, merged